# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDFD8eekEAqQqoYCVlQvHUPPa8PPvuQ6
"""

# ==========================================
# AI & ML Internship - Task 1
# Data Cleaning & Preprocessing


import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import kagglehub
from sklearn.preprocessing import LabelEncoder, StandardScaler

# 1.Import the dataset and explore basic info (nulls, data types)
path = kagglehub.dataset_download("yasserh/titanic-dataset")
print("Path to dataset files:", path)

# Load CSV file
file_path = os.path.join(path, "Titanic-Dataset.csv")
df = pd.read_csv(file_path)

print("\nFirst 5 Rows:")
print(df.head())

print("\nDataset Info:")
print(df.info())

print("\nMissing Values Before Handling:")
print(df.isnull().sum())

# 2. Handle missing values using mean/median/imputation.


# Fill Age with median
df['Age'].fillna(df['Age'].median(), inplace=True)

# Fill Embarked with mode
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

# Drop Cabin column (too many missing values)
if 'Cabin' in df.columns:
    df.drop('Cabin', axis=1, inplace=True)

print("\nMissing Values After Handling:")
print(df.isnull().sum())

#3. Convert categorical features into numerical using encoding.

le = LabelEncoder()

df['Sex'] = le.fit_transform(df['Sex'])
df['Embarked'] = le.fit_transform(df['Embarked'])

# 4.Normalize/standardize the numerical features.
columns_to_drop = ['Name', 'Ticket', 'PassengerId']
df.drop([col for col in columns_to_drop if col in df.columns],
        axis=1, inplace=True)


# 5.Visualize outliers using boxplots and remove them.


plt.figure(figsize=(8,4))
sns.boxplot(data=df[['Age','Fare']])
plt.title("Boxplot for Age and Fare")
plt.show()

Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1

df = df[~((df < (Q1 - 1.5 * IQR)) |
          (df > (Q3 + 1.5 * IQR))).any(axis=1)]

print("\nShape After Removing Outliers:", df.shape)


# 6. Feature Scaling (Standardization)

scaler = StandardScaler()
scaled_data = scaler.fit_transform(df)

df_scaled = pd.DataFrame(scaled_data, columns=df.columns)

print("\nFinal Processed Data (First 5 rows):")
print(df_scaled.head())

# 7. Save Cleaned Dataset

df_scaled.to_csv("cleaned_titanic.csv", index=False)

print("\n✅ Preprocessing Completed Successfully!")